export const skillSections = [
  {
    title: "Programming Languages",
    directory: "programmingLanguages",
    skills: ["JavaScript", "TypeScript", "Java", "Kotlin", "SQL"],
  },
  {
    title: "Web Technologies",
    directory: "webTechnologies",
    skills: ["HTML", "CSS", "HTML5", "Rest APIs / JSON"],
  },
  {
    title: "Frameworks & Libraries",
    directory: "frameworksAndLibraries",
    skills: [
      "React",
      "React 18",
      "Vue 3",
      "NextJS 14",
      "Ember",
      "Node.js",
      "AngularJS",
      "Tailwind",
      "MaterialUI",
      "Ant Design",
      "DaisyUI",
      "Redux",
      "VueX",
      "GraphQL",
    ],
  },
  {
    title: "Testing",
    directory: "testing",
    skills: ["Cypress", "Jest"],
  },
  {
    title: "Tools & Platforms",
    directory: "toolsAndPlatforms",
    skills: [
      "Git",
      "Github",
      "npm / yarn",
      "Jira / Bitbucket",
      "Strapi",
      "Supabase",
      "Figma",
      "Sentry",
      "Apollo",
      "Jenkins",
      "Datadog",
      "CircleCI",
      "Bash",
    ],
  },
  {
    title: "UI/UX Design",
    directory: "uiUxDesign",
    skills: ["Figma"],
  },
  {
    title: "Templating Engines",
    directory: "templatingEngines",
    skills: ["Handlebars"],
  },
  {
    title: "HobbiesAndInterests",
    directory: "hobbiesAndInterests",
    skills: ["📚 Reading", "🎬 movies", "🎮 Gaming"],
  },
];
